### ISSUE TITLE
Cannot install through Opam in macOS 12.2.1 M1 chip

### ISSUE THREAD

**Issue by ignatirabo** [nberth/mlgmpidl#14]
Hello,

I have been trying to install `apron` which depends on `mlgmpidl`. Problem is during the installation the script is not able to find GMP which I installed through `homebrew`.

I notice that it would be easy if I could manually set the `GMP_PREFIX` flag from what I googled, but I do not know how to do this or what other fix I can try.
Also I don't know if I should install GMP in another way, or maybe even install `mlgmpidl` manually.

This is the output of the installation:
```
$ opam install mlgmpidl
The following actions will be performed:
  - install mlgmpidl 1.2.14

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> retrieved mlgmpidl.1.2.14  (cached)
[ERROR] The compilation of mlgmpidl.1.2.14 failed at "sh ./configure --absolute-dylibs".

#=== ERROR while compiling mlgmpidl.1.2.14 ====================================#
# context     2.1.2 | macos/arm64 | ocaml.4.12.0 | https://opam.ocaml.org#0a4c2bf0
# path        ~/.opam/default/.opam-switch/build/mlgmpidl.1.2.14
# command     ~/.opam/opam-init/hooks/sandbox.sh build sh ./configure --absolute-dylibs
# exit-code   1
# env-file    ~/.opam/log/mlgmpidl-3719-2f5e9f.env
# output-file ~/.opam/log/mlgmpidl-3719-2f5e9f.out
### output ###
# [...]
# binary perl: found in /opt/homebrew/bin
# binary install: found in /usr/bin
# looking for gmp without prefix
# include gmp.h: not found
# looking for gmp in prefix /usr/local
# include gmp.h: not found
# looking for gmp in prefix /usr
# include gmp.h: not found
# looking for gmp in prefix /Users/tiraboschi
# include gmp.h: not found
# library gmp not found
# GMP not found, set GMP_PREFIX



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build mlgmpidl 1.2.14
+-
- No changes have been performed
```

Any help is appreciated. Thanks in advance.

**Comment by nberth** [comment]
Hi,

I've  heard that `homebrew` now install things a little differently indeed. Could you try to locate where `libgmp` is installed? Possibly somewhere within `/opt`.  Then you'll be able to set `GMP_PREFIX` (and `MPFR_PREFIX`) appropriately.

**Comment by ignatirabo** [comment]
Hello,

I found the library in `/opt/homebrew/lib` but I am not sure how to set this prefix. Would you be so kind to guide me in setting it?

Thank you!

**Comment by nberth** [comment]
Ok in principle something like `GMP_PREFIX=/opt/homebrew MPFR_PREFIX=/opt/homebrew opam install mlgmpidl` should do it.

**Comment by ignatirabo** [comment]
Hello,

Thank you very much! This was exactly the issue.
