### ISSUE TITLE
string and bytes

### ISSUE THREAD

**Issue by channgo2203** [nberth/mlgmpidl#2]
In the file mpfr.ml, there is a build error because of the use of string instead of bytes with OCaml 4.0.6
"File "mpfr.ml", line 551, characters 2-3:
Error: This expression has type string but an expression was expected of type bytes
"

**Comment by nberth** [comment]
Thanks for reporting this issue. An updated version of `mlgmpidl` that compiles with OCaml ≥ 4.06 should be released soon.

**Comment by vbgl** [comment]
Here is a  patch:
~~~
diff --git a/mpfr.idl b/mpfr.idl
index ce21046..3ae20f1 100644
--- a/mpfr.idl
+++ b/mpfr.idl
@@ -332,8 +332,7 @@ let (s,e) = get_str ~base:10 ~digits:0 x Near in \n\
 if s = \"\" \n\
 then \"0.\" \n\
 else if s.[0] = '-' then begin\n\
-  Bytes.set s 0 '.';\n\
-  Format.sprintf \"-0%sE%i\" s e\n\
+  Format.sprintf \"-0.%sE%i\" String.(sub s 1 (length s - 1)) e\n\
 end\n\
 else Format.sprintf \"0.%sE%i\" s e \n\
 ")
~~~

**Comment by nberth** [comment]
@vbgl thanks indeed. The new package is already prepared and I will release it soon, but I am first inspecting some other packages I develop/maintain to see if there are more efficient means to enforce string immutability in camlidl-generated bindings.

What is it with 4.06 that people want so much to rush into it so fast?

**Comment by channgo2203** [comment]
Thanks all for the quick reply and patch.

About the question, I have no idea. However, I think personally that people
using OCaml almost are on Mac OS or Linux.
And it is common that they do apt-get upgrade or brew upgrade. As a result,
the latest version of OCaml
comes.

Best,

**Comment by nberth** [comment]
mlgmidl.1.2.6 fixes this issue
