### ISSUE TITLE
Dynamic native library (.cmxs) is not compiled anymore

### ISSUE THREAD

**Issue by vprevosto** [nberth/mlgmpidl#3]
It seems that commit 454e47fc790156fa8bb884594c57a5c4a7fcb93a did remove `HAS_NATIVE_PLUGINS` from `Makefile.config`, as seen in [this line of the diff](https://github.com/nberth/mlgmpidl/commit/454e47fc790156fa8bb884594c57a5c4a7fcb93a#diff-e2d5a00791bce9a01f99bc6fd613a39dL52) for `configure` (possibly it was intended to replace it with `HAS_SHARED`, which seems to appear in this [other line](https://github.com/nberth/mlgmpidl/commit/454e47fc790156fa8bb884594c57a5c4a7fcb93a#diff-e2d5a00791bce9a01f99bc6fd613a39dR403)).

However, the `Makefile` itself still relies on the presence of this variable to decide whether to create `gmp.cmxs` or not, effectively preventing it to be created, thus to dynamically load the library in native applications.

An obvious workaround is to compile with `make HAS_NATIVE_PLUGINS=1` (or to `export HAS_NATIVE_PLUGINS=1` before `opam reinstall mlgmplib`), but it'd obviously be better to either define `HAS_NATIVE_PLUGINS` in `Makefile.config`, rely on `HAS_SHARED` in `Makefile`, or, given that the variable was apparently unconditionally set to `1`, get rid of the test altogether.

**Comment by nberth** [comment]
Thanks for reporting this issue. I indeed applied a few changes from another branch that might have used other make variables after all… I'll make a new release (or update that one once again) soon to correct that.

**Comment by vprevosto** [comment]
Thanks for the quick reply. In fact, I just notice there is also an issue in bytecode, but I haven't been able to pinpoint it so far. Trying to load `gmp` ends up in the following error (while dynamic loading in native code works fine on the same installation)

```
utop # #require "gmp";;
Cannot load required shared library dllgmp_caml.
Reason: /home/virgile/.opam/4.05.0/lib/stublibs/dllgmp_caml.so: /home/virgile/.opam/4.05.0/lib/stublibs/dllgmp_caml.so: undefined symbol: mpfr_agm.
```

**Comment by vprevosto** [comment]
For the record, I've just installed commit 9b5e2d6faa56e91cfe8f and everything is fine, both with native and bytecode dynamic loading. Thanks for the quick fix.
