### ISSUE TITLE
Rounding modes are not working

### ISSUE THREAD

**Issue by andrejbauer** [nberth/mlgmpidl#4]
It seems like the rounding mode is always `Down` no matter what I set.  I am on OSX, Ocaml 4.04.1, MFPR is version 3.1.2-p11. Here is a small concrete example:

    (* Testing rounding modes in Mpfr. *)

    Mpfr.set_default_rounding_mode Mpfr.Up ;;

    let x = 32.0 +. 0.001 /. 3.0 ;;

    Format.printf "x = %F@." x ;;

    let a : Mpfr.t = Mpfr.of_float x Mpfr.Down ;;

    Format.printf "a (Down) = %t@." (fun ppf -> Mpfr.print ppf a) ;;

    let b : Mpfr.t = Mpfr.of_float x Mpfr.Up ;;

    Format.printf "b (Up) = %t@." (fun ppf -> Mpfr.print ppf b) ;;

    (* What if we copy b to b' with low precision and tell it to round up? *)
    let b' = Mpfr.init2 4 ;;

    ignore (Mpfr.set b' b Mpfr.Up) ;;

    Format.printf "b' (Up) = %t@\n@." (fun ppf -> Mpfr.print ppf b') ;

This gives the following output:

    x = 32.0003333333
    a (Down) = 0.32000333333333330E2
    b (Up) = 0.32000333333333330E2
    b' (Up) = 0.320E2

As far as I am concrned `b` should be larger than `x`.

**Comment by nberth** [comment]
Andrej Bauer <notifications@github.com> writes:

> It seems like the rounding mode is always Near no matter what I set. I
> tracked this down to camlidl_mpfr_rnd_t_ml2c in gmp_caml.h where it
> says that for MPFR major version >= 3 the rounding mode si always
> Near. What is up with that? Could we get this fixed?

If you're using OPAM, can you tell me what version of mlgmpidl you are
using?

-- 
Nicolas Berthier

**Comment by nberth** [comment]
Indeed there was a bug in older versions of mlgmpidl, with regards to rounding mode arguments. In your example though, assignments to `a` and `b` are correct, as `of_float` does not involve any rounding with the default precision. The actual bug is in the assignment to `b'` with 4 bits precision: rounding up should give 36 instead of 32.

Yet, I could reproduce your execution with mlgmpidl 1.2.5, but 1.2.6 is okay w.r.t your example:

    x = 32.0003333333
    a (Down) = 0.32000333333333330E2
    b (Up) = 0.32000333333333330E2
    b' (Up) = 0.360E2

**Comment by andrejbauer** [comment]
Ah. Let me see how to get my hands on 1.2.6. OPAM claims that only 1.2.4 is available. Could we get that updated?

**Comment by andrejbauer** [comment]
It seems that I need to update OPAM. Sorry for the noise and many thanks! For documentation purposes, could you quickly state what the bug was?

**Comment by nberth** [comment]
The fix is in commit 29c22a2bdf205dcc0dc19195d56b2a9633dd104d. OCaml int values encoding rouding modes were passed to the C side without the proper conversion.

**Comment by andrejbauer** [comment]
I am having trouble getting 1.2.6. For some reason OPAM (1.2.0) doesn't see it when I do `opam update`, it only goes up to 1.2.4. Do I have to go to OPAM 2? (Sorry to bother you.)

**Comment by nberth** [comment]
Andrej Bauer <notifications@github.com> writes:

> I am having trouble getting 1.2.6. For some reason OPAM (1.2.0)
> doesn't see it when I do opam update, it only goes up to 1.2.4. Do I
> have to go to OPAM 2? (Sorry to bother you.)

What do `opam info mlgmpidl.1.2.6` and `opam install mlgmpidl.1.2.6`
tell you?

-- 
Nicolas Berthier                                        FSF Member #7975

**Comment by andrejbauer** [comment]
I wish OPAM had better documentation. I was at 1.2.0 and should have been at 1.2.2. Thanks for your help!
