### ISSUE TITLE
Fixing some return types, adding some functions

### ISSUE THREAD

**Issue by tturpin** [nberth/mlgmpidl#5]
Hi,

I am planing to use mlgmpidl in some software developed by my company, MathWorks. In this process I have found that a few functions had been incorrectly typed as returning a boolean instead of a "ternary value". Also, I needed a few additional functions which were not yet stubbed. Finally, I found it useful to provide a (very simple) interface to sprintf. This may or not be of general interest.

I'm sending the patch to mpfr.idl as an attachement. Please let me know if I should create a pull request.
[mpfr.idl.txt](https://github.com/nberth/mlgmpidl/files/2224470/mpfr.idl.txt)

Best Regards,
Tiphaine Turpin
MathWorks

**Comment by nberth** [comment]
Hi,

Thanks for reporting these issues and your contribution. I just noticed I had fixed some of those function signatures already, but will add your additions promptly. I will also create a new OPAM package, and hopefully it'll make its way easily into the official repository.

Best,
Nicolas

**Comment by tturpin** [comment]
Wonderful ! You are right about the safe string issue, I forgot about that.

Tiphaine
