### ISSUE TITLE
Build failure on platforms where profiling is not available

### ISSUE THREAD

**Issue by vbgl** [nberth/mlgmpidl#6]
The OCaml compiler does not support profiling on all platforms. Whether profiling is supported can be checked calling `ocamlopt -config | grep profiling`.

When building `mlgmpidl` in such an environment, compilation fails with:
> Profiling with "gprof" is not supported on this platform.

Here is an example of the log of a failed attempt to build: https://logs.nix.ci/?key=nixos/nixpkgs.55951&attempt_id=ecf69320-30a1-46d7-9437-734cd6e6af8a

Could the build of the profiling-enabled libraries be made optional?

**Comment by nberth** [comment]
Sure! Commit 2aa5393609c1acb246eb19dffbac2eefd8ff181e fixes that I guess. Are you able to test it before I make a release through OPAM?

Thanks for reporting this issue.

**Comment by vbgl** [comment]
Thanks! I’ll try to test and then report here.

**Comment by vbgl** [comment]
This does not work. See https://logs.nix.ci/?attempt_id=95367e81-de40-4221-a04f-c9affca70bdb&key=nixos%2Fnixpkgs.56154.

`ocamlopt -config` outputs:
> cc_profile: -pg
> profiling: false

**Comment by nberth** [comment]
Haha! not all versions of OCaml output this `profiling:' thingy then. I'll take it into account when it shows up then.

**Comment by nberth** [comment]
Commit a0235d5 should handle cases where profiling is disabled whereas profiling flags are provided

**Comment by vbgl** [comment]
Maybe in the “not supported” case, should the `enable_prof` variable be set to 0.

**Comment by nberth** [comment]
Oh yes indeed. My bad I did that very quicky before leaving and overlooked it. Thanks again.
Edit: see commit 2c2441d91fe6067ad744f698a2a

**Comment by vbgl** [comment]
Thanks! That worked (log of a build success: https://logs.nix.ci/?attempt_id=fbebe138-228d-4654-af76-b4522fd18844&key=nixos%2Fnixpkgs.56154).

**Comment by nberth** [comment]
Ok great! I'll also push a release through OPAM soon.
