### ISSUE TITLE
Unspecified behavior w.r.t. Pervasives.compare

### ISSUE THREAD

**Issue by pascalito** [nberth/mlgmpidl#8]
The modules Mpzf, Mpqf and Mpfr (and more) offer comparison functions:
`cmp : t -> t -> int`

- Experimentally, it seems that Pervasives.compare dispatches on these functions.
- Yet, in the IDL files, no typedef contains the `compare(...)` attribute.
- The documentation of MLGMPIDL gives no information on that aspect.

Could the documentation of MLGMPIDL state clearly if it is sound (or not) to use Pervasive.compare on its values?

**Comment by nberth** [comment]
Yes from what I can see `Pervasives.compare` dispatches to the respective `cmp` functions on these types:  it's all setup in `gmp_caml.c` actually. I'll document that somewhere (yet I myself have no control over the online documentation on the inrialpes.fr webside).

Thanks for reporting this issue.

**Comment by pascalito** [comment]
Thanks for the answer and precisions.
