### ISSUE TITLE
Mpfr.to_mpq is not working

### ISSUE THREAD

**Issue by pascalito** [nberth/mlgmpidl#9]
Calling Mpfr.to_mpq abruptly halted my program with:
> gmp: overflow in mpz type
> Aborted

I join to this issue a program with two calls to Mpfr.to_mpq : 

- one producing an incorrect result,
- one producing the failure mentioned above.

[minimal_bug_mpfr_to_mpq.ml.txt](https://github.com/nberth/mlgmpidl/files/3232203/minimal_bug_mpfr_to_mpq.ml.txt)

With my version of MLGMPIDL (1.2.9), this program produces this output:

> ## Unsoundness ##
> The float: 0.56294995342131200E23
> The rational: 800000000
> ## Crash ##
> The float: 0.10000000000000000E1
> gmp: overflow in mpz type
> Aborted

In my humble opinion, the code of Mpfr.to_mpq has never been functional, for any input. The failure arises when the mpz_mul_2exp is called with a negative exponent (which is almost always the case). I propose the patch attached to this issue (I could not push my branch directly).
[mpfr_to_mpq.diff.txt](https://github.com/nberth/mlgmpidl/files/3231618/mpfr_to_mpq.diff.txt)

The patch fixes the failure and gives correct results. My argumentation is detailed below:

The documentation of MPFR says:

> Function: mpfr_exp_t mpfr_get_z_2exp (mpz_t rop, mpfr_t op) 
>     Put the scaled significand of op (regarded as an integer, with the precision of op) into rop, and return the exponent exp (which may be outside the current exponent range) such that op exactly equals rop times 2 raised to the power exp.

The documentation of GMP says:

> Function: void mpz_mul_2exp (mpz_t rop, const mpz_t op1, mp_bitcnt_t op2)
>     Set rop to op1 times 2 raised to op2. This operation can also be defined as a left shift by op2 bits. 

and:

> Counts of bits of a multi-precision number are represented in the C type mp_bitcnt_t. Currently this is always an unsigned long, but on some systems it will be an unsigned long long
in the future.

From the GMP documentation, it is clear that mpz_mul_2exp must not be called with directly with a value of type mpfr_exp_t, which can be negative.

From a significand sig and exponent exp, the proposed code computes:

- when exp is negative: sig / (2 ^ -exp),
- when exp is positive: (sig * 2 ^ exp) / 1

Both computation boils down to sig * 2 ^ exp, which happen to be the input value.

With the patch applied, the attached program produces the following output:

> ## Unsoundness ##
> The float: 0.56294995342131200E23
> The rational: 56294995342131200000000
> ## Crash ##
> The float: 0.10000000000000000E1
> The rational: 1

**Comment by nberth** [comment]
@pascalito Thanks a lot for reporting this issue along with a patch! In case, a release will make its way through OPAM shortly.

**Comment by pascalito** [comment]
And thanks for maintaining!
